### ISSUE TITLE
`TcpSuite` hangs if there is an error in `accept`

### ISSUE THREAD

**Issue by armanbilge** [armanbilge/epollcat#28]
When a suite hangs this usually means there is a resource leak, since the `ExecutionContext` won't stop polling for events until all file-descriptors and associated callbacks have been deregistered.

**Comment by armanbilge** [comment]
I believe this is a bug in our test suite, not our implementation.

The problem is here:
https://github.com/armanbilge/epollcat/blob/f87cccc976c43fb0693ec4a56e9c59b9215b1d2c/tests/shared/src/test/scala/epollcat/TcpSuite.scala#L145

When the `server` is `.background`ed, then any exceptions thrown in the background are not raised any further. Screaming into the void essentially 😉

**Comment by LeeTibbert** [comment]
Is that also why the `connect` error gets swallowed?   

I have spent most of Labor Day chasing that one.  Learned a lot, but did not catch it.
I think I did manage to convince myself that the server has gotten past bind
(hence has a defined local port) before the background task starts execution.

My IPv6 code is, I believe, revealing several more general problems.  The IPv6
code is, essentially, fault injection.  The problems are not seen with IPv4,
either SN or JVM, but they are latent there.

I believe the fault chain is that `connect()` is properly complaining that it has
been given a server address where no one is listening, so it, properly,
throws a ConnectException. (Yes it happens, I did printf's)

The 'ping-pong' code ignores the ConnectException, probably for the reason you 
pointed out.   

`accept()` never receives a connection attempt at the address where it
is listing (because client was given wrong address, tried once, and failed).
`accept()` was called with no timeout mechanism, so it appears to 
hang when it is only doing what it was tasked with doing: hang out and listen
for a connection which will never come.)

So, two errors here and related Issue:  ignoring ConnectException and
no timeout to `accept()`.  Fixing the first one will mask the second.
I think fixing the second first, then the first will lead to more
robust test code. 

BTW:   I have been searching for the documentation, in epoll files & cats-effect IO, for
`async_`  I have found docs for `async` (and the different but, I think, related `Async`).
Have I missed something?  Is the trailing underbar a convention which I have missed
in my rocket sled epoll/cats-effect education?

**Comment by armanbilge** [comment]
> Is that also why the `connect` error gets swallowed?

No, I'm afraid not :( I remembered you had a hanging issue as well. The client is running in the foreground so the error should be raised. If you can push a branch/PR that reproduces this issue I can investigate it. Sorry for the wild goose chase on your part!

---

> BTW: I have been searching for the documentation, in epoll files & cats-effect IO, for
> `async_` I have found docs for `async` (and the different but, I think, related `Async`).

`async_` is a simplified, non-cancelable version of `async`. The scaladoc is here:
https://typelevel.org/cats-effect/api/3.x/cats/effect/IO$.html#async_[A](k:(Either[Throwable,A]=%3EUnit)=%3EUnit):cats.effect.IO[A]
